"""Generate `HeroIcons.kt`: Heroicons Outline (MIT, Tailwind Labs) as Compose ImageVectors.

Usage:
    npm pack heroicons@2.2.0 && tar -xzf heroicons-2.2.0.tgz
    python scripts/generate-heroicons.py path/to/package

Only icons referenced as `HeroIcons.<Name>` somewhere under app/src are emitted,
so adding an icon is: use `HeroIcons.ArrowDownTray` in code, re-run this script.
`<Name>` is the Heroicons file name in PascalCase (`arrow-down-tray` ->
`ArrowDownTray`). CUSTOM holds a few glyphs Heroicons lacks, drawn on the same
24px grid with the same 1.5px round stroke; `@name` reuses a Heroicons path.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "app" / "src"
OUT = SRC / "main" / "java" / "app" / "aino" / "mobile" / "core" / "designsystem" / "icons" / "HeroIcons.kt"

SLASH = "M3 3l18 18"
CUSTOM = {
    "Circle": ["M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"],
    "Square": ["M3.75 6A2.25 2.25 0 0 1 6 3.75h12A2.25 2.25 0 0 1 20.25 6v12A2.25 2.25 0 0 1 18 20.25H6A2.25 2.25 0 0 1 3.75 18V6Z"],
    "SquareCheck": [
        "M3.75 6A2.25 2.25 0 0 1 6 3.75h12A2.25 2.25 0 0 1 20.25 6v12A2.25 2.25 0 0 1 18 20.25H6A2.25 2.25 0 0 1 3.75 18V6Z",
        "m8.25 12.75 2.25 2.25 5.25-6",
    ],
    "DoubleCheck": ["m2.25 12.75 3.75 3.75 7.5-9", "m11.25 15.75.75.75 7.5-9"],
    "Keyboard": [
        "M3.75 6.75h16.5a1.5 1.5 0 0 1 1.5 1.5v7.5a1.5 1.5 0 0 1-1.5 1.5H3.75a1.5 1.5 0 0 1-1.5-1.5v-7.5a1.5 1.5 0 0 1 1.5-1.5Z",
        "M6 10.5h.008M9 10.5h.008M12 10.5h.008M15 10.5h.008M18 10.5h.008M8.25 14.25h7.5",
    ],
    "MicrophoneSlash": ["@microphone", SLASH],
    "CloudSlash": ["@cloud", SLASH],
    "WifiSlash": ["@wifi", SLASH],
    "PushPin": ["M9 3.75h6M9.75 3.75V9l-3 3.75h10.5L14.25 9V3.75M12 12.75v7.5"],
    "Infinity": ["M7.5 8.25c-2.07 0-3.75 1.68-3.75 3.75s1.68 3.75 3.75 3.75c3 0 6-7.5 9-7.5 2.07 0 3.75 1.68 3.75 3.75s-1.68 3.75-3.75 3.75c-3 0-6-7.5-9-7.5Z"],
    "Cup": [
        "M4.5 9.75h11.25v4.5a4.5 4.5 0 0 1-4.5 4.5H9a4.5 4.5 0 0 1-4.5-4.5v-4.5Z",
        "M15.75 11.25h1.5a2.25 2.25 0 0 1 0 4.5h-1.5",
        "M8.25 3.75v2.25M12 3.75v2.25",
    ],
    "Text": ["M4.5 7.5V4.5h15v3M12 4.5v15M9 19.5h6"],
}
# Directional glyphs flip in right-to-left layouts, like Material's AutoMirrored set.
MIRRORED = re.compile(r"^(Arrow(Left|Right|Uturn|LongLeft|LongRight|SmallLeft|SmallRight|Turn)|Chevron(Left|Right|DoubleLeft|DoubleRight)|PaperAirplane|Backspace)")


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("-"))


def main() -> None:
    package = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("package")
    outline = package / "24" / "outline"
    svgs = {pascal(p.stem): p for p in outline.glob("*.svg")}
    if not svgs:
        sys.exit(f"No Heroicons found under {outline}")
    by_file = {p.stem: p for p in outline.glob("*.svg")}

    def paths_of(svg: Path) -> list[str]:
        return re.findall(r'<path[^>]*\sd="([^"]+)"', svg.read_text(encoding="utf-8"))

    used = set()
    for kt in SRC.rglob("*.kt"):
        if kt == OUT:
            continue
        used.update(re.findall(r"\bHeroIcons\.([A-Z]\w*)", kt.read_text(encoding="utf-8")))

    entries = []
    for name in sorted(used):
        if name in CUSTOM:
            paths = []
            for item in CUSTOM[name]:
                paths += paths_of(by_file[item[1:]]) if item.startswith("@") else [item]
        elif name in svgs:
            paths = paths_of(svgs[name])
        else:
            sys.exit(f"HeroIcons.{name} is not a Heroicons Outline icon or CUSTOM glyph")
        args = ", ".join(f'"{p}"' for p in paths)
        mirror = ", mirrored = true" if MIRRORED.match(name) else ""
        entries.append(f'    val {name}: ImageVector by lazy {{ hero("{name}", {args}{mirror}) }}')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/generate-heroicons.py - do not edit by hand.\n"
        "// Heroicons Outline v2.2.0, MIT License, Copyright (c) Tailwind Labs, Inc.\n"
        "// Full notice ships in assets/licenses/heroicons-LICENSE.txt.\n"
        "package app.aino.mobile.core.designsystem.icons\n\n"
        "import androidx.compose.ui.graphics.Color\n"
        "import androidx.compose.ui.graphics.SolidColor\n"
        "import androidx.compose.ui.graphics.StrokeCap\n"
        "import androidx.compose.ui.graphics.StrokeJoin\n"
        "import androidx.compose.ui.graphics.vector.ImageVector\n"
        "import androidx.compose.ui.graphics.vector.addPathNodes\n"
        "import androidx.compose.ui.unit.dp\n\n"
        "/** App icon set: Heroicons Outline (24px grid, 1.5px round stroke). `Icon(tint = ...)` recolours the stroke. */\n"
        "object HeroIcons {\n" + "\n".join(entries) + "\n}\n\n"
        "private fun hero(name: String, vararg paths: String, mirrored: Boolean = false): ImageVector =\n"
        "    ImageVector.Builder(\n"
        "        name = \"HeroIcons.$name\", defaultWidth = 24.dp, defaultHeight = 24.dp,\n"
        "        viewportWidth = 24f, viewportHeight = 24f, autoMirror = mirrored,\n"
        "    ).apply {\n"
        "        paths.forEach {\n"
        "            addPath(\n"
        "                addPathNodes(it), stroke = SolidColor(Color.Black), strokeLineWidth = 1.5f,\n"
        "                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round,\n"
        "            )\n"
        "        }\n"
        "    }.build()\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Wrote {len(entries)} icons to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
